    name: Deploy to Firebase Hosting

    on:
      push:
        branches:
          - main # IMPORTANT: Change this to 'master' if your default branch is 'master'

    jobs:
      build_and_deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4 # Checks out your repository code
          - name: Deploy to Firebase Hosting
            uses: FirebaseExtended/action-hosting-deploy@v0 # This GitHub Action handles the deployment
            with:
              repoToken: '${{ secrets.GITHUB_TOKEN }}'
              firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' # Uses the secret you just created
              projectId: project-asar # Your Firebase project ID
              channelId: live # Deploy to your live site
